- i18n/XaoS_cs.ts
- i18n/XaoS_de.ts
- i18n/XaoS_es.ts
- i18n/XaoS_fr.ts
- i18n/XaoS_hi.ts
- i18n/XaoS_hu.ts
- i18n/XaoS_is.ts
- i18n/XaoS_it.ts
- i18n/XaoS_pt.ts
- i18n/XaoS_ro.ts
- i18n/XaoS_rs.ts
- i18n/XaoS_ru.ts
- i18n/XaoS_sk.ts
- i18n/XaoS_sv.ts
- src/ui-hlp/ui_helper.cpp
- src/ui/main.cpp
- Add missing translation in Status (bailout was forgotten). I added the TR function in the code and added translation in all .ts files when "bailout" was translated in other contexts
- Add QtBase Translator => allow to translate buttons liks Apply / Cancel / Ok / Open in system windows (like save / open windows)
- some spelling in french translation
> Add missing translation, add qtBaseTranslator for generic window transaltions

- src/util/timers.cpp
Fixes build failure with GCC 10, which had some header dependency
changes:  https://gcc.gnu.org/gcc-10/porting_to.html
> Include cstdlib for calloc/free

- src/util/xstdio.cpp
Fixes #152 
This PR changes the size of buffer for filenames, this fixes the persisting issue.
> Fix Buffer Overflow issue

- src/util/xstdio.cpp
After #156 the crashes remained on using record function when starting from blank, this PR fixes them.
> Fix crashes on blank recording

- src/ui-hlp/render.cpp
Rendering through command line produced seg fault errors due to assigning font to uih_context - gc1
(NULL) when called from command line.
Fixed in this.
> Fix Seg fault while rendering from cli

- src/ui/main.cpp
- src/util/xmenu.cpp
The last implementation shown help message along with error message on every unavailable commands.
Now the errors message is produced as:
```
> xaos -unavailable function
> unavailable function:unknown function
Please enter `xaos -help` to learn more on command line options
```
PS: This is part 1 of #155
> Invalid Commands only produce error message

- src/include/misc-f.h
- src/include/ui_helper.h
- src/ui-hlp/menu.cpp
- src/ui-hlp/ui_helper.cpp
- src/ui/image_qt.cpp
Type : Enhancement
Fixes #128 
Changes:
Added option to 'Open Image' under File menu.T
This option allows to save & open PNG without XPF data.
> Save xpf data in png chunk

- src/ui-hlp/ui_helper.cpp
- src/ui/image_qt.cpp
Invalid PNGs/ with no metadata now produces error
Read more #166
> Show error message on non xaos pngs

- src/include/filter.h
- src/include/xmenu.h
- src/ui-hlp/menu.cpp
- src/ui/customdialog.cpp
- src/ui/customdialog.h
- src/util/palette.cpp
Part of #165 
What's new?
This PR will add feature for users to know beforehand the color palette going to be generated.
Where to see changes?
In GUI menu, Fractal->Palette->Custom Palette
> Added Gradient to Custom palette

- src/include/xmenu.h
- src/ui-hlp/menu.cpp
- src/ui/customdialog.cpp
- src/ui/customdialog.h
- src/util/xmenu.cpp
Type: Enhancement, Palette, GUI
This is a follow up of #168 
What's New?
Removed Current values fields from the dialog box.
How does it look?
> Removed Current Values option from Custom Palette

- src/include/grlib.h
- src/include/ui_helper.h
- src/ui-hlp/menu.cpp
- src/ui-hlp/ui_helper.cpp
- src/ui/image_qt.cpp
Issues: Fixes #122 
What's New?
Cartesian Grid added.
How to use?
Go to View -> Cartesian grid -> Enable
Keyboard: Press 'g'
Sample:
Current Shortcomings:
Cartesian Grid is only available until 100000x zoom levels i.e. in coordinate axis terms not fractal zoom terms.
Ps. There is a small unrelated change to fix some bugs introduced by #169
> Add cartesian grid

- src/ui-hlp/ui_helper.cpp
Removes grid text from Cartesian grid display
The same status can be obtained through ```Size``` parameter in ```Status```
> Remove grid text

- src/ui-hlp/ui_helper.cpp
- src/ui/image_qt.cpp
Fixes #174 
Tested with Catalina 10.15.3 :)
> Fix Paths for handling XaoS Images

- src/ui-hlp/ui_helper.cpp
- src/ui/image_qt.cpp
After #176, saving images on mac failed sometimes due to memory leak issues in Mac.
This PR resolves it.
Fixes #174
> Fix saving image on Mac in 4.1pre1 

- src/include/misc-f.h
- src/include/ui_helper.h
- src/ui-hlp/render.cpp
- src/ui-hlp/ui_helper.cpp
- src/ui/image_qt.cpp
Fixes #179 
Potential Fix for #174 (to be checked)
This removes dependency over temporary file used in ver 4.1 for saving images with xaos and reading them back.
> Do not use temporary an XPF file when saving/loading from a PNG

- src/include/xmenu.h
- src/ui-hlp/menu.cpp
- src/ui/customdialog.cpp
- src/ui/customdialog.h
Issue: #129 
What's New?
Now users can render multiple files together using batch rendering option. The files names will be in format: (Base_Name)_(File_Number)_(XXXXX) - this means users can batch render animation files and xpf files together with no collisions.
Where to find the option?
Files -> Batch Render
UI:
> Support for Batch Rendering

- src/include/xmenu.h
- src/ui-hlp/menu.cpp
- src/ui/customdialog.cpp
- src/ui/customdialog.h
Reverts xaos-project/XaoS#184
The patch basically works well, but I found the following issues:
* It seems that displayed messages can be mixed between animations.
* The naming would be better to be related with the original filenames and not the selection number.
* If this patch works correctly, we no longer need the Render... menu. But instead of removing it, I suggest we use the Render... menu and allow selection of multiple files in that menu.
> Revert "Support for Batch Rendering"

- src/include/xmenu.h
- src/ui-hlp/menu.cpp
- src/ui/customdialog.cpp
- src/ui/customdialog.h
After #184 , there were some changes regarding batch rendering
> The patch basically works well, but I found the following issues:
> It seems that displayed messages can be mixed between animations.
> The naming would be better to be related with the original filenames and not the selection number.
> If this patch works correctly, we no longer need the Render... menu. But instead of removing it, I suggest we use the Render... menu and allow selection of multiple files in that menu.
These are addressed in this PR
> Improve Rendering

- src/ui-hlp/menu.cpp
Framerate and always recalculate options are now removed from render image menu.
> Remove extra options from Render Image Menu

- src/ui-hlp/ui_helper.cpp
Issue: Fixes #115 
Panning while rotation didn't used to work/ was erratic before XaoS 4.1. This fix solves it.
This fix first disables rotation only the first time panning starts, does panning, and continues rotation. On complex fractals with slower boundary trace users may face some loading time while starting panning.
> Fix Panning while rotation

- src/ui-hlp/menu.cpp
- src/ui-hlp/ui_helper.cpp
- src/ui/customdialog.cpp
- src/ui/image_qt.cpp
- src/ui/mainwindow.cpp
Issue #190 
This PR unifies Open and Open Image menu options. Now ```Open``` is able to load png and xpf both.
Save Image has been shifted to ```Save as``` and  ```Save``` remains as it is.
```Save as``` should get populated in future when xaos starts supporting more export formats.
Ps. Should we rename Save as to Export as ?
> Unify open/ open image and save/ save image

- src/include/filter.h
- src/include/xmenu.h
- src/ui-hlp/menu.cpp
- src/ui/customdialog.cpp
- src/ui/customdialog.h
- src/util/palette.cpp
- src/util/xmenu.cpp
Fixes #15 #165 
What was added?
Option to choose custom color palette from 31 base colors ranging from outside most to inside.
Where to find?
Fractal -> Palette -> Palette Picker
Screenshots -:
Future Scope:
User should be able to load/ download the color profile in a extension such as ```.gpl``` for easily sharing it across system or reusing it.
> Add Custom Palette aka Palette Picker

- src/ui-hlp/menu.cpp
- src/ui/customdialog.cpp
Fixes #193 
What's new?
Easy loading and sharing of palette as a ```.gpl``` extension file.
Press ```x``` to launch palette picker
> Add ability to save/load palette

- src/ui-hlp/menu.cpp
- src/ui/customdialog.cpp
From #194 loading and saving of palette was introduced.
- Users can now open the palette config file ```.gpl``` with GIMP/ or can manually edit it.
- Options are now moved to Fractal -> Palette -> as ```Load Palette Config``` and ```Save Palette Config```
> Improve load/ save palette config

- src/include/filter.h
- src/include/ui_helper.h
- src/ui-hlp/menu.cpp
- src/ui-hlp/save.cpp
- src/ui/image_qt.cpp
Fixes #196 
XPF file and PNG now contains palette colors. The colors are to be passed in hex format.
Sample xpf file:
```
;Position file automatically generated by XaoS 4.1
;  - a realtime interactive fractal zoomer
;Use xaos -loadpos <filename> to display it
(initstate)
(defaultpalette 0)
(palettecolors "ffffff" "fce94f" "180719" "c5421c" "1d120b" "872e47" "181b0d" "f1e680" "111f18" "f0a28b" "0b041e" "6a57bd" "1d150e" "0c8c76" "0a061d" "32904d" "160018" "94bcf3" "042007" "e7920e" "0a0d14" "b89344" "0d1c03" "a9f898" "040022" "3e5330" "071516" "9861b8" "08030c" "f75ceb" "1f2010")
(formula 'mandel)
(view -0.75 0 2.5 2.5)
```
Using Command Line:
```
xaos -palettecolors  "ffffff" "fce94f" "180719" "c5421c" "1d120b" "872e47" "181b0d" "f1e680" "111f18" "f0a28b" "0b041e" …
```
> Save palette colors to XPF and PNG

- src/include/config.h
- src/ui/main.cpp
Fixes #164 
Added: ```Help -> Info on current fractal``` opens up the wiki for the current fractal at https://github.com/xaos-project/XaoS/wiki/Fractal-Types
> Add current fractal information help menu

- src/ui-hlp/menu.cpp
- src/ui/customdialog.cpp
- src/ui/customdialog.h
Please see discussion on #200 
```Saved user formulas``` option removed
`User formula` now keeps history of last 10 user formulas used.
> Keep record of used user formulas

- src/ui/main.cpp
Needed on some systems because of the `setlocale(LC_NUMERIC, "C");` line.
> fix: add missing header

- src/ui/main.cpp
Previously, thread initialization happened before command line
parameter parsing, causing pth_init() to not get the value
provided via the -threads parameter.
> Move thread initialization after parameter parsing, fixing #227

- README.md
The current website link just leads to a redirect. This helps in futureproofing in case the redirect goes down.
> Fix website link in README

- xdg/xaos.appdata.xml
> Error: Error on line 119 char 14: Element “releases” was closed, but the currently open element is “release”
> Fixed invalid AppStream XML

- i18n/README.md
Adding alphabetical order requirement in i18n/README.md for new languages.
> Adding alphabetical order requirement in README for new languages
